---
dev_binary:
  - url: https://code.visualstudio.com/docs/?dv=linux64_deb
    dest: "/tmp/vscode.deb"

dev_deb:
  - /tmp/vscode.deb

dev_config:
  - src: "settings.json"
    dest: "~/.config/Code/User/settings.json"
  - src: "extensions"
    dest: "/tmp/extensions"
